useIsDraggingWithin 🪝
sixach/wp-react-hooks pull request #87
Opened 2022-03-04 20:59 UTC by mahdiyazdani

This PR introduces a new hook to determine whether an element is being dragged within another (ref) target element.

2022-03-05 19:36 UTC, gooklani approved these changes
Thank you @mahdiyazdani 👍

2022-03-05 22:34 UTC, kuserich requested changes
Thank you, @mahdiyazdani . Would you be able to elaborate on this function, just for my understanding? Given that we add the event listener to referenced element, I would assume that the event callback is always executed, if a draggable child is targeted (since the event bubbles up to the parent nodes). In that case, `isDraggingWithin` should always be `true` if something is dragged and only be `false` on drag end.

2022-03-05 22:34 UTC, kuserich commented on src/useIsDraggingWithin/index.js
> +			if ( elementRef.current.contains( event.target ) ) {
Just a tiny detail: since we're assigning `ownerDocument` on line 32, we would be able to reuse it here as well

2022-03-05 22:34 UTC, kuserich commented
> Thank you, @mahdiyazdani . Would you be able to elaborate on this function, just for my understanding? Given that we add the event listener to the ref element, I would assume that the event callback is always executed, if a draggable child is targeted (since the event bubbles up to the parent nodes). In that case, `isDraggingWithin` should always be `true` if something is dragged and only be `false` on drag end.

2022-03-05 23:06 UTC, mahdiyazdani commented
> Would you be able to elaborate on this function, just for my understanding?

@kuserich Basically, this is a [borrowed](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-widgets/src/blocks/widget-area/edit/use-is-dragging-within.js) function exported from the Gutenberg core as, for some reason, they haven’t exposed it to be imported in third-party projects yet.

2022-03-07 15:39 UTC, kuserich commented
> > Would you be able to elaborate on this function, just for my understanding?
> 
> @kuserich Basically, this is a [borrowed](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-widgets/src/blocks/widget-area/edit/use-is-dragging-within.js) function exported from the Gutenberg core as, for some reason, they haven’t exposed it to be imported in third-party projects yet.

Okay, I see 😄  thanks for elaborating

2022-03-09 18:42 UTC, merged